//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.21 at 06:16:47 PM IST 
//


package inheritance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cat1" type="{http://example.com/}Animals"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cat1"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected Animals cat1;

    /**
     * Gets the value of the cat1 property.
     * 
     * @return
     *     possible object is
     *     {@link Animals }
     *     
     */
    public Animals getCat1() {
        return cat1;
    }

    /**
     * Sets the value of the cat1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Animals }
     *     
     */
    public void setCat1(Animals value) {
        this.cat1 = value;
    }

}
